name: We Micro Give
favicon: null
layout_spectrum: 0.645260518649593
typography_spectrum: 0.06865845923312008
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9242682247422636
  lightness: 0.3432184364646673
  saturation: 0.43771572364494205
  rhythmicContrast: 0.07105136127211154
purpose: []
